# -*- coding: utf-8 -*-
"""Random.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/175XyWydqMmrH_xVc5rUZg8kKGQ6OYVid
"""

import random

chute = int(input('Digite um número'))
x = random.randint(1,7)

if chute == x:
    print('acertô', x)
else:
    print(f'errou, era {x}')

import random

alt = random.randrange(5,8)
print(alt)

import random

alt1 = random.randrange(1,2,3)
alt2 = random.randrange(5,6,7)
alt3 = random.randrange(8,9,12)

print(alt1, alt2, alt3)

import random

n3 = random.randrange(10,30)
print(n3)