# -*- coding: utf-8 -*-
"""Exercicios_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VOYo_aYRGNvuaK7-vANMPqdBFJx7RcaV
"""

numero = int(input('digite um número inteiro '))

if numero > 0:
    print(numero, "é positivo")

elif numero == 0:
    print('é zero')

else:
    print(numero, 'é negativo')

l1 = int(input('digite um valor inteiro '))
l2 = int(input('digite um valor inteiro '))
l3 = int(input('digite um valor inteiro '))

if l1 == l2 == l3:
    print("triangulo equilatero")

elif l1 >= l2 and l3:
    print("triangulo isoceles")

else:
    print("triangulo escaleno")

ano = int(input("Digite um ano "))

if int(ano/4) and int(ano/400):
    print('é um ano bissexto')

elif ano == int(ano/100):
    print('é um ano bissexto')

else:
    print('Não é um ano bissexto')
