# -*- coding: utf-8 -*-
"""Exercício_11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NmaU-r-5OXQIEhEZNPmfYS7Nr7tTWBF1
"""

nome = lambda a: print(a-1)
print(nome(10))

soma = lambda lista: sum(lista)
numeros = [1,2,3,4,5]
total = soma(numeros)
print(total)
numeros = [7,8,9,4,3]
total = soma(numeros)
print(total)

lista = [1,2,3,4,5]
lista1 = list(map(lambda x: x**2, lista))
print('lista= ', lista,'\n\nlista1=',lista1)

from functools import reduce
lista = [1,2,3,4,5,6]
produto = reduce(lambda x,y: x*y, lista)
print('lista = ',lista,'\n\nproduto=',produto)

lista = [1,2,3,4,5]
lista1 = list(filter(lambda x:x%2 !=0, lista))
print('lista=',lista,'\n\nlista1=',lista1)

#1

dobro = lambda x: x*2
print(dobro(2))

#2

soma = lambda x, y: x+y
print(soma(10,2))

#3

num1 = lambda x: x%2==0
print(num1(2))

#4

mai = lambda s: s.upper()
print(mai('uai'))

#5

produto = lambda x,y,z: x*y*z
print(produto(2,5,2))