# -*- coding: utf-8 -*-
"""Exercicios_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Z7ljWxXF6zQ9gB4Cz-gZkaKMqg0mR9y
"""

nome = input('qual é o seu nome? ')
print('prazer em te conhecer', nome)

hora = 20
minuto = 30
segundo = 14
print("A hora é", hora,":", minuto,":",segundo)

ddd = input('qual ddd? ')
telefone = input('qual seu número? ')
print ("(",ddd,")", telefone)

i1 = input('Ingreditente 1 ')
i2 = input('Ingreditente 2 ')
i3 = input('Ingreditente 3 ')
i4 = input('Ingreditente 4 ')
print("Seus ingredientes são: ", i1,",", i2,",", i3,"e", i4)

nome = input('qual é o seu nome? ')
rep = input("qual palavra mais te representa? ")
fazer = input('o que gosta de fazer? ')
sente = input('como você se sente? ')
print('Você é', nome, 'e a palavra', rep, 'te representa como pessoa, gosta de', fazer, 'e sent-se', sente)