# -*- coding: utf-8 -*-
"""exercício_14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eroD-xIrR8VDsYcVKArGoP7D_q_HMEzw
"""

#Método Join

text = 'Finalmente sextou'

a = 'bom dia'.join(text)
print(a)

palavras = ["Olá", "mundo", "em", "Python"]
frase = " ".join(palavras)  # Concatena os elementos da lista com um espaço em branco entre eles
print(frase)  # Isso imprimirá "Olá mundo em Python"

tex = 'ola mundo'

t = tex[:3]
print(t)

#1 Remova o último elemento de uma lista e imprima a lista resultante.

lista = [1, 2, 3, 4, 5]
lista.pop(4)
print(lista)

#2 Remova o elemento de índice 2 de uma lista e imprima a lista resultante

lista = [10, 20, 30, 40, 50]
lista.pop(1)
print(lista)

#3 Crie uma pilha usando uma lista e implemente as operações append e pop.

lista = [1, 2, 3, 4, 5]
lista.pop(2)
lista.append(30)
print(lista)

#4Remova o primeiro elemento de uma lista e o último elemento usando pop() e imprima a lista resultante.

lista = [1, 2, 3, 4, 5]
lista.pop(0)
lista.pop(3)
print(lista)

#5 Acesse os três primeiros caracteres de uma string.

frase = "opa, bão?"
f = frase[:3]
print(f)

#6 Acesse todos os elementos de uma lista, exceto o primeiro e o último.

lista = [1,2,3,4,5,6,7]
lista1 = lista[1:6]
print(lista1)

#CALCULADORA DE MÉDIA

n1 = float(input('Por favor, insira a primeira nota: '))
n2 = float(input('Por favor, insira a segunda nota: '))
n3 = float(input('Por favor, insira a terceira nota: '))

resultado = n1+n2+n3
resultado2 = resultado/3

if resultado2 >= 7 and resultado2 < 10:
    print('Aprovado')

if resultado2 >= 5 and resultado2 < 7:
    print('Recuperação')

if resultado2 < 5:
    print('Reprovado')

elif resultado2 > 10:
    print('Inserir um valor de 0 a 10 apenas.')