# -*- coding: utf-8 -*-
"""Exercício_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RUnIMaO_j5A5Dj-KH3RSrVtY4_t8omYE
"""

numero1 = 4
numero2 = 2
print(numero1 ** numero2)

nome = 'Eduardo'
sobrenome = 'Tavares'
print(nome + ' ' + sobrenome)

n1 = "1"
n2 = "4"
print(n1+n2)

palavra = "Python"
numero = input('digite um numero')

print(palavra+numero)