# -*- coding: utf-8 -*-
"""Exercício_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qLTTP5AG9DgIMprc87wf0Ao1DSuzm-UC
"""

#1
for num in range(1,6):
  print(num)

#2
n1 = range(1,7)
n4 = n1[4]
print(n4)

#3
lista = [1,2,3,4,5]
lista.append(6)
print(lista)

#4
lista = [1,2,3,4,5]
lista.remove(2)
print(lista)

#5
fruta = 'maça','uva','manga'
ni = 0
for numero in fruta:
  ni+=1
  print(ni, numero)

#6
lista = ['maça','uva','manga']
for frutas in lista:
  print(frutas)

#7
numeros = [1,3,6,5,25,16]
if 5 in numeros:
    print("o número está")
else:
    print('não tem')