# -*- coding: utf-8 -*-
"""exercício_12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11UbnFWr_74vY5Ejv2GdLprK1b1kPGy3B
"""

# nome_conjunto = {1,3,4,5,6}
# print(nome_conjunto)

conjunto2 = {12,52,63,1,3,5}
conjunto3 = {12,63,5,2}

print(conjunto2.difference(conjunto3))
print(conjunto3.difference(conjunto2))

#1 Transforme uma lista em um conjunto

lista1 = [1,2,3]
conv = set(lista1)
print(conv)

#2 Una estes 2 conjuntos

zone = {1, 2, 3, 4}
kwia = {3, 4, 5, 6}

uni = zone.union(kwia)
print(uni)

#3 Verifique a diferença entre os conjuntos:

g1 = {12,3569,1,5,7}
g2 = {12,3569,2,5,8}

diff = g1.difference(g2)
print(diff)

4#

frutas = {'maçã', 'banana', 'laranja', 'pêra', 'abacaxi'}
print(len(frutas))

#5

conjunto1 = {7,8,9}
conjunto2 = {6,5,4}

con = conjunto1.union(conjunto2)
print(con)

#6

cores = {'azul','vermelho','verde','amarelo'}
cores.remove('vermelho')
print(cores)

#7

numeros = {1,2,3,4,5,6,7,8,9,10}
imp = {1,3,5,7,9}
pares = numeros.difference(imp)
print(pares)

#8

alunos_aprovados = {'ana','rick','maria','clara',}
todos_alunos = {'joão','ana','alice','rick','gustavo','maria','isa','clara','hector','pedro','lucas','alemão'}
if alunos_aprovados in todos_alunos:
    print('estão')
else:
    print('não estão')

#8 subs

alunos_aprovados = {'ana','rick','maria','clara',}
todos_alunos = {'joão','ana','alice','rick','gustavo','maria','isa','clara','hector','pedro','lucas','alemão'}

diff = todos_alunos.difference(alunos_aprovados)
print(diff)