# -*- coding: utf-8 -*-
"""(extra)_Calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14XNnfC5QajvTxKeKhU6YVH-Vb7ywfd8G
"""

def calculadora(x,y):
    print('soma - ', x + y)
    print('subtração - ', x - y)
    print('divisão - ', x / y)
    print('multiplicação - ', x * y)

calculadora(10,20)
