# -*- coding: utf-8 -*-
"""Exercicio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynezOvZLvqXbAWljYrKeeND5ib0dI3Gh
"""

numero_real = 1.5
print(numero_real)

nome = 'josé'
print('Olá', nome)

nome = input('Digite seu nome ')

numero1 = 4
numero2 = 2
print(numero1 ** numero2)

Nome = input('Seu nome ')
Sobrenome = input('Seu sobrenome ')

print (Nome + Sobrenome)

numero = int (input('digite um numero'))
numero2 = int(input('digite mais um numero'))
resultado = numero + numero2

print(resultado)

palavra = "Python"
numero = input('digite um numero')

print(palavra+numero)

